### ISSUE TITLE
Mensagens flash acentuadas não estão sendo mostradas

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/copaco#135]

**Comment by leandroramos** [comment]
Estou tentando reproduzir o erro. Você se lembra de alguma situaçao em que ele ocorreu?

![erros acentuados](https://user-images.githubusercontent.com/3253741/38145404-7563e78e-341f-11e8-8848-71335ce8da8e.png)

**Comment by thiagogomesverissimo** [comment]
![captura de tela de 2018-04-04 14-40-11](https://user-images.githubusercontent.com/908508/38324278-2c6ab83c-3816-11e8-830e-9c2d3007ac1c.png)
