### ISSUE TITLE
Remover CDNs do jquery e bootstrap e compilar usando webpack/nodejs

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/copaco#16]

**Comment by girol** [comment]
Acho que vc poderia fazer isso numa live e ensinar noiz. qq acha? 🌟 :shipit:

**Comment by thiagogomesverissimo** [comment]
@girol claro!
Vamos combinar no próximo pindura como faremos esse esquema de pequenas apresentações.

**Comment by thiagogomesverissimo** [comment]
Nas aulas 20 e 21 tem como é feito esse procedimento https://www.youtube.com/playlist?list=PLlJiqaCtsRWDOFg85nvRtOY33Y6-caOZr

mas como aqui o adminlte usado que carrega essas libs externas não precisamos fazer.
