### ISSUE TITLE
Implementar perfis e segmentação de usuário por subrede

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/copaco#167]
Segmentar usuários para gerenciar suas próprias subredes com perfis administrador e subrede.
Esta issue pode ser dividida em outras issues.

**Comment by thiagogomesverissimo** [comment]
A estratégia que penso em usar:

 - Criar uma área para gerência de grupo (que vão ser os gates do laravel)
 - Criar uma área para gerência dos usuários (podemos mudá-lo de grupo nesta área)
 - Fazer o relacionamento entre rede e grupo

**Comment by alecostaweb** [comment]
Se criar uma coluna admins na tabela redes e nesta coluna armazenar o número usp dos donos da rede já resolve.

**Comment by thiagogomesverissimo** [comment]
Acho que a gerência por grupos fica organizada. =)

**Comment by alecostaweb** [comment]
:+1:

**Comment by thiagogomesverissimo** [comment]
E na física funciona assim também, com grupos, então vamos tentar nao quebrar o ambiente da sybele.
