### ISSUE TITLE
Só validar o Patrimônio quando a opção "Equipamento não patrimoniado" estiver desmarcada

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/copaco#177]
Assim, podemos tirar a validação de valores empty na rule Patrimonio.
Esse issue depende da PR 175 ser aceita

**Comment by girol** [comment]
Na verdade o valor empty é desnecessário. Tem como validar isso no front/back se e somente se o dado existe na request. Se jogar um JS maroto dá pra resolver isso.
