### ISSUE TITLE
Corrigir tema CSS da aplicação

### ISSUE THREAD

**Issue by leandroramos** [uspdev/copaco#188]
O tema está quebrado, alguns componentes fora de lugar (checkboxes, radios, etc)

**Comment by girol** [comment]
Lembrando que o tema quebrou com a introdução dessa PR: #178

**Comment by girol** [comment]
Galera, acontece o seguinte:

Eu fiquei batendo cabeça agora aqui com o tema que """"Quebrou"""" depois da PR do @alecostaweb .

Na verdade, eu acho que o Alê consertou o tema. A gente tava usano o tema semi quebrado desde o começo. O arquivo que buga é [esse aqui](https://github.com/uspdev/copaco/blob/master/resources/assets/sass/app.scss).

Com a introdução do pacote de fontes que o alê colocou, os menus voltaram a funcionar com `:hover` entre outras coisas.

Removendo o `app.css` do `master.blade.php` ele "desbuga" mas se a gente for comparar com o tema original tirado da página do Bootstrap, o que a gente adaptou não tem absolutamente nada a ver.

O que acham de dar uma refatorada nesse front pra melhorar o visual e já padronizar?

Eu arrisco ser diferença de versão do bootstrap. O Dashboard foi feito na versão alpha.

**Comment by alecostaweb** [comment]
Acho legal refatorar isso. O único objetivo era incluir o ícone :bust_in_silhouette: separado do link Sair. Já que vamos refatorar, que tal pensarmos no front, onde teremos ícones, hover e outras coisas para implementarmos sem os bugs?

**Comment by girol** [comment]
Eu queria instalar o AdminLTE pra ficar legal, mas talvez seja demais pra simplicidade da interface. Se vcs quiserem eu monto.

**Comment by alecostaweb** [comment]
Voto SIM para o AdminLTE! :+1:
