### ISSUE TITLE
Criar tabela de perfis ou não?

### ISSUE THREAD

**Issue by leandroramos** [uspdev/copaco#190]
Pensei em criar uma tabela para os perfis de usuário.
Mas o @alecostaweb me lembrou de que os perfis/papéis/roles/grupos (o nome que quiserem) são as próprias redes que cadastramos no sistema. Levanto a questão:

É melhor criar uma tabela com os perfis (com mesmo nome da rede) ou gravar os números USP do pessoal no próprio cadastro da rede?

**Comment by alecostaweb** [comment]
Posso estar falando besteira, mas se adicionar uma coluna users na tabela redes e guardarmos uma string com os números usp separados por vírgula de quem pode gerenciar esta rede já resolveria.

**Comment by leandroramos** [comment]
Também estou preferindo essa forma, apenas um campo a mais na tabela redes. Vou ver se temos mais alguma opinião antes de mudar as migrations.

**Comment by alecostaweb** [comment]
Sim, mas se pensar que uma vez logado no sistema e não for admin, o usuário pode adicionar equipamentos nas redes dele. Somente o admin pode adicionar rede e incluir usuário nesta rede. Parece muito simples, mas já resolve por exemplo que:
O técnico de infomática do Departamento de Biblioteconomia pode incluir equipamento na rede de Biblioteconomia. O objetivo é dar autonomia para alguns técnicos locados em departamentos dentro das unidades. Sim, o exemplo é da ECA. rs.

**Comment by thiagogomesverissimo** [comment]
Essa issue está duplicada. Vou fechá-la para concentrarmos a conversa em https://github.com/uspdev/copaco/issues/167
