### ISSUE TITLE
 Verificar compatibilidade do jQuery

### ISSUE THREAD

**Issue by girol** [uspdev/copaco#227]
Pois são usadas versões distintas do que tínhamos antes e agora.

**Comment by thiagogomesverissimo** [comment]
Mas você achou algum conflito em específico?

**Comment by girol** [comment]
Lembro de ter visto uns warnings malucos no inspector do Browser

**Comment by wgnann** [comment]
Isso não é decorrente de incluirmos dois jqueries? Um é incluido via não-sei-o-quê e o outro fica no js.blade.php.

Percebi isso quando estava mexendo com jquery e não conseguia esconder um modal.

**Comment by girol** [comment]
@wgnann foi o que eu percebi na época também. o tema fica todo disgramado do jeito que tava com 2 jquery

**Comment by wgnann** [comment]
eu meramente removi o jquery de lá e está funcionando. talvez compense testar e colocar isso num PR
