### ISSUE TITLE
Implementar delete para Equipamento

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/copaco#24]

**Comment by thiagogomesverissimo** [comment]
@leandroramos vc não já implementou essa issue?

**Comment by leandroramos** [comment]
Já implementei sim, @thiagogomesverissimo 
As outras issues que peguei dependem dos formulários. Farei depois do hangout de hoje.

**Comment by leandroramos** [comment]
Na verdade não, @thiagogomesverissimo. Implementei junto com uma outra que foi cancelada. Estou fazendo agora.

**Comment by leandroramos** [comment]
Minha memória está falhando. Essa PR ficou aberta para referência de código. Mas fiz outro commit tirando os try/catches dela. Veremos na bagunça mais tarde.
