### ISSUE TITLE
Possibilitar cadastrar redes e equipamentos que não apareçam no dhcpd.conf

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/copaco#241]
Ao clicar em dhcpd.conf informar:
- Todas as redes
- Rede 1
- Rede 2
- Rede 3
- ...
Desta forma, pode-se cadastrar equipamentos que não necessariamente esteja no range de DHCP. Ex.: Servidores.

**Comment by thiagogomesverissimo** [comment]
Mas não faria muito sentido, pois como o sistema vai gerar o dhcpd.conf sem conhecer a rede?
