### ISSUE TITLE
adicionar possibilidade de inserir mask ao invés de cidr. mas no banco manter cidr, por conta do pos processamento

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/copaco#299]

**Comment by wgnann** [comment]
pelo que eu entendi, o que queremos é: verificar se é um IP de máscara e transformar em CIDR ou um CIDR (e não fazer nada). correto?

**Comment by thiagogomesverissimo** [comment]
Isso. Mas é firula, quem gerência redes consegue converter mask para cidr e vice-versa. Fechando issue.
