### ISSUE TITLE
Melhoria no README.md

### ISSUE THREAD

**Issue by wgnann** [uspdev/copaco#324]
Em vez de dizer:

> Caso já tenha rodado o comando anteriormente, dê um refresh:
> 
> php artisan migrate:refresh
> 
> 

O guia deveria dizer algo como:
Caso precisar recriar o usuário, precisa dar refresh antes:

php artisan migrate:refresh
php artisan copaco:setup_dev

Fiquei um tempo pensando que refresh era para atualizar alguma estrutura (tipo migration mesmo) no modo dev. :P

**Comment by thiagogomesverissimo** [comment]
Esse comando não existe mais:
`
php artisan copaco:setup_dev`
