### ISSUE TITLE
atributo 'naopatrimoniado' deveria chamar 'patrimoniado'

### ISSUE THREAD

**Issue by wgnann** [uspdev/copaco#329]
naopatrimoniado é true se o equipamento tiver patrimônio...

**Comment by thiagogomesverissimo** [comment]
Sim, ficou uma merda o jeito que está...
Vou tentar alterar isso

**Comment by thiagogomesverissimo** [comment]
corrigido.
Na verdade campo naopatrimoniado removido, pois não fazia sentido neste sistema.
