### ISSUE TITLE
rotas de login múltiplas

### ISSUE THREAD

**Issue by wgnann** [uspdev/copaco#331]
A ideia é generalizar a rota de login e fazer algo do tipo `/login/<mecanismo>` e daí ele chama o mecanismo correto. Precisaremos, também, configurar um mecanismo padrão que será o configurado para receber o `/login`.

Daí podemos colocar aqueles botõezinhos para o usuário escolher o mecanismo de login.

**Comment by thiagogomesverissimo** [comment]
Só recapitulando, os métodos seriam>

 - oauth (já implemenetado)
 - local (em vias de ser implementado)
 - ldap (não implementado. Devo essa a @sybgroff  do IFUSP, pois lá usam mais senha ldap que senha única)

**Comment by wgnann** [comment]
Estava vendo sobre como o Laravel implementa login via LDAP. Uma das formas é usar um provider específico, mas não vi como fazer para usar dois providers diferentes para a mesma finalidade. Pensei em fazer no LDAP a mesma coisa que ser faz com o OAuth: recebe os dados relevantes e é isso aí.

Talvez não seja possível fazer fácil o que eu imaginara: usar uma rota genérica `/login/<mecanismo>` e trabalhar a autenticação de forma abstrata.

**Comment by thiagogomesverissimo** [comment]
Não sei se chegou a ver o readme, mas implementei uma opção de criação de usuário local. Podemos implementar ldap também.
