### ISSUE TITLE
fornecer um mecanismo padrão de autenticação

### ISSUE THREAD

**Issue by wgnann** [uspdev/copaco#332]
Hoje o copaco assume que o usuário terá um token de oauth ou que usaremos um hackzinho no `redirectToProvider()` para permitir acesso sem o oauth.

A ideia é gerar um `make:auth` que permita o livre cadastro de usuários e a possibilidade de testar os roles (já que haverá mais de um usuário possível no sistema).

O problema em fazer isso é que o `make:auth`, por padrão, sobrescreve a rota do `/login` para usar o método `login()` em vez do `redirectToProvider()`.

**Comment by thiagogomesverissimo** [comment]
Eu opto por remover o hackzinho do redirectToProvider() e implementar mesmo o login de usuário local baseado em token, isto é, só se registra quem tem um token.

**Comment by wgnann** [comment]
Parece trivial. Basta gerar o `make:auth` e mudar as rotas de `/register` para receberem o token que estará no arquivo de configuração.

**Comment by thiagogomesverissimo** [comment]
O login local está implementado. Chegou a testar?
