### ISSUE TITLE
fornecer um mecanismo de autorização para unidades

### ISSUE THREAD

**Issue by wgnann** [uspdev/copaco#333]
Não necessariamente queremos que usuários de todas as unidades tenham acesso ao Copaco. Donde parece necessária a implementação de um mecanismo de controle de acesso que corta pelo menos por unidade (ou conjunto de).

Talvez seja interessante, ainda, aumentar a granularidade para barrar, por exemplo, determinados tipos de vínculo de fazer cadastro (e.g. alunos de graduação em alguns casos de uso).

**Comment by thiagogomesverissimo** [comment]
Acha que devemos usamos o retorno do OAuth para fazer esse filtro ou conectamos esse sistema no replicado ?

 - **Prós replicado:** as queries para montar esses filtros já estão prontas em https://github.com/uspdev/replicado

 - **contra replicado**: obrigaríamos que as unidades tenham o replicado para usar o copaco

**Comment by wgnann** [comment]
Depende do filtro. O de unidade vem via OAuth e o trabalho para lidar com isso é zero (está no PR).

Acho que dá para fazer tudo com o OAuth. O único problema é que eu não sei qual é o conjunto de coisas. Precisaríamos mapear o `tipoVinculo` para saber com quais casos lidaremos. Em particular, no IME, o público alvo do Copaco é: alunos de pós, professores e funcionários (estagiários inclusos). Aparentemente só excluiremos os alunos de graduação (que é o que está no PR, por ora).

**Comment by thiagogomesverissimo** [comment]
Com o retorno da senha única podemos barrar o acesso pelos grupos retornados. Bastaria especificarmos no .env os grupos permitidos. O que acha?
