### ISSUE TITLE
gerador de dhcp ainda usa método lerdo

### ISSUE THREAD

**Issue by wgnann** [uspdev/copaco#335]

**Comment by thiagogomesverissimo** [comment]
sim, o culpado é esses foreach encadeados em Controllers/DhcpController.php: 
```
        foreach ($redes as $rede) {
        ....
            $equipamentos = $rede->equipamentos;
            foreach ($equipamentos as $equipamento) {
                ....
        }
    }

```

**Comment by wgnann** [comment]
O culpado é o getRange. Vou refatorar tudo que usa o NetworkOps para fazer contas em vez de gerar uma lista com 2^n IPs. Verifiquei, inclusive, que o que é chamado da NetworkOps é o seguinte:
`database/factories/EquipamentoFactory.php`
  -> getRange(): objetivo é escolher um ip aleatório no intervalo
  
`database/factories/RedeFactory.php`
  -> getRange(): quer o primeiro IP da rede

`app/Utils/Freeradius.php`
  -> cria a instância e não usa pra nada

`app/Http/Controllers/EquipamentoController.php`
  -> aloca(): verifica / reserva um IP para o equipamento

`app/Http/Controllers/FreeradiusController.php`
  -> não cria nem a instância

`app/Http/Controllers/DhcpController.php`
  -> getRange(): encontra o começo do range, o final e o broadcast

`app/Rules/PertenceRede.php`
  -> pertenceRede(): usado para validar se um IP está na rede
