### ISSUE TITLE
Permitir registrar um equipamento numa rede sem fixar seu IP

### ISSUE THREAD

**Issue by wgnann** [uspdev/copaco#338]
Isso inclui, ainda, fazer esse equipamento aparecer no dhcpd.conf (sem o endereço fixado).

**Comment by thiagogomesverissimo** [comment]
Você diz, selecionar uma rede mas sem fixar o ip, neste caso o servidor dhcp se vira e não esse sistema. 
Acha que vale a pena? Pois o núcleo desse sistema é fazer isso.
