### ISSUE TITLE
Gerar dhcpd.conf com hosts em cada linha

### ISSUE THREAD

**Issue by wgnann** [uspdev/copaco#339]
Deixar as entradas de host em mais de uma linha mata possíveis greps no /etc/dhcpd.conf. Não parece mudar em nada deixar cada entrada numa linha (embora facilite processar o arquivo posteriormente).

**Comment by thiagogomesverissimo** [comment]
Nossa nem tinha pensado nisso. Realmente, ficaria muito melhor. Quer implementar ou eu o faço?
