### ISSUE TITLE
Permitir que se faça uma solicitação de inclusão de mac address sem estar autenticado

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/copaco#340]
Explicando melhor...
Sem estar autenticado, alguém acessa a página, preenche alguns campos básicos de identificação e contato, além do mac address e a subrede, e o sistema informa o responsável pela subrede para autorizar ou não a inclusão.

**Comment by wgnann** [comment]
Mas não é melhor a pessoa se autenticar e cadastrar ela mesma as coisas?

**Comment by alecostaweb** [comment]
No cenário que pensei não. Quando um professor/visitante/palestrante/convidado, etc, sem nº. USP vem até a unidade para ficar um determinado tempo (uma semana ou mais) em algum departamento e quer plugar seu note/pc na rede por exemplo.

**Comment by wgnann** [comment]
Aí não seria suficiente solicitar o cadastro para qualquer pessoa que tenha credenciais (e.g. secretaria do departamento, algum colega etc)? Tem que existir algum responsável, de preferência de fora da seção de informática, pelos equipamentos "alienígenas".

**Comment by alecostaweb** [comment]
Sim, por isso citei a autorização no primeiro comentário. A diferença é que mesmo que a pessoa não tenha nº USP ou cadastro no sistema, ela pode usar o sistema para solicitar o acesso de seu equipamento "alienígena" :smile:

**Comment by wgnann** [comment]
Mas como o operador do copaco vai conseguir autenticar que o pedido veio de alguém? Vai ser algo tipo:
1. O visitante que não tem eduroam quer Internet;
2. Ele liga para a STI;
3. A STI acredita nele e sugere que ele faça o cadastro;
4. A STI aprova o cadastro.
Como saber que é um visitante que faz sentido?

Ou
1. O visitante que não tem eduroam quer Internet;
2. Ele fala com alguém da secretaria do departamento que visita;
3. A secretaria sugere para ele cadastrar o equipamento e entra em contato com a STI;
Sucesso. (exceto que a própria secretaria poderia ter feito o cadastro, pois sabe que o visitante é visitante)

**Comment by alecostaweb** [comment]
Quase...
1. O visitante não é da USP, logo sem eduroam, sem senha única e sem qualquer tipo de acesso ao sistema copaco, ok?
2. O visitante acessa um formulário público, sem logar, no copaco e preenche os campos de identificação, contato, mac adress do equipamento "alienígena" e a qual subrede/departamento pertence (se souber) e envia.
3. O responsável pela subrede/sistema recebe uma notificação, verifica se procede e aprova via sistema copaco se o equipamento "alienígena" deve ser plugado na internet.

**Comment by wgnann** [comment]
O passo de verificar a procedência é que é o passo difícil. Como isso seria feito? (teoricamente, já é possível fazer um formulário que informa pessoas)

**Comment by alecostaweb** [comment]
Na real o que incomoda é alguém ligar e passar o mac address por telefone/ramal, e-mail, chamado técnico e etc.
Quanto a verificar a procedência... Digamos que o responsável pela subrede teria que pelo menos fazer isso de forma presencial.
Mas blz, talvez não faça sentido.
