### ISSUE TITLE
$user->id = $userSenhaUnica->codpes?

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/copaco#341]
@wgnann , 

No seu último PR você re-inseriru essa linha para usuários provindos da senha única:
`$user->id = $userSenhaUnica->codpes;`

Acha interessante que o id seja igual ao número USP para pessoas USP?
Não entendi o porque da mudança.

**Comment by thiagogomesverissimo** [comment]
Perguntas, caminhos...

1. esconder id do usuário e portanto dos templates
2. verificar porque id é incrementado a partir do número USP quando esses dois deveriam ser independentes
3 decidir se vamos colocar um campo apenas para username ou username_ldap, username_senhaunica, username_local. 
4. adicionar mais um campo na tabela usuário no qual registramos quais métodos de login o usuário já usou?

**Comment by wgnann** [comment]
O porquê da mudança? Essencialmente pq o adminlte estava usando o id e não o negócio que tem o NUSP para exibir os nomes de usuário. Só reforçando o que já foi dito, o ideal é deixar o id independente, como você sugeriu, e deixar o NUSP fazer o papel de username ou algo parecido.

**Comment by wgnann** [comment]
> Perguntas, caminhos...
> 
>     1. esconder id do usuário e portanto dos templates
Acho que não precisa.
> 
>     2. verificar porque id é incrementado a partir do número USP quando esses dois deveriam ser independentes
Não faço ideia. Não consegui reproduzir numa instalação limpa. Deve ser alguma coisa errada no MySQL.

>        3 decidir se vamos colocar um campo apenas para username ou username_ldap, username_senhaunica, username_local.
Para mim, o ideal é ter um campo só e o mecanismo de autenticação adaptar as coisas para o modelo utilizado no Copaco. A única situação onde faz sentido ter mais de um username é se usássemos efetivamente o mesmo id para dois mecanismos de autenticação diferentes. Mas não sei o que ganharíamos com isso.

> 
>     3. adicionar mais um campo na tabela usuário no qual registramos quais métodos de login o usuário já usou?
Isso parece acoplar as coisas a menos que o objetivo seja permitir que um mesmo usuário consiga utilizar diversos mecanismos de autenticação. A única coisa que parece conveniente é quando um dos mecanismos de autenticação cai.

Por outro lado, um modelo onde seja possível transferir a responsabilidade de equipamentos (implementado no IME edition porcamente) parece mais desejável.
