### ISSUE TITLE
Pesquisar por responsável no ambiente de admin

### ISSUE THREAD

**Issue by wgnann** [uspdev/copaco#342]
A busca permite procurar por 'Patrimônio, mac address, local ou descrição', mas pode ser conveniente para um admin procurar, também, por equipamentos de um dado responsável.

**Comment by thiagogomesverissimo** [comment]
Eu e vitor mexemos um pouco nos filtros. Buscar pelo resonsável seria bacana mesmo.

@v1t4o poderia tentar incluir essa busca?
