### ISSUE TITLE
O campo última alteração não faz sentido

### ISSUE THREAD

**Issue by wgnann** [uspdev/copaco#343]
O última alteração usa o responsável pelo equipamento e não o responsável pelo cadastro. O responsável pelo cadastro inexiste, na realidade. Talvez compense separar essas duas semânticas, a saber:
  * quem é o responsável pelo equipamento (em geral um não admin);
  * quem editou informações sobre um dado equipamento (admin ou o responsável mesmo).

**Comment by wgnann** [comment]
update: depois do PR #345 a lista que é gerada com links quebrados.

**Comment by thiagogomesverissimo** [comment]
qual lista?

**Comment by thiagogomesverissimo** [comment]
Mas aproveitando, eu estou aqui quebrando a cabeça se usamos username para tudo, incluindo rotas. Exemplo: as rotas são baseadas em id atualmente e não em username, então meu user por exemplo tem endereço /user/3 e não /user/thiago. Os ids foram escondidos dos templates (isso deve ter quebrados algumas coisas por enquanto). Mas vamos propagar username nas rotas também, o que acha?

**Comment by wgnann** [comment]
> qual lista?

a lista de equipamentos. aparece o campo de "última alteração" e os hrefs vão para o username em vez do id

**Comment by wgnann** [comment]
> Mas aproveitando, eu estou aqui quebrando a cabeça em uma decisão: usamos username para tudo, incluindo rotas? Exemplo: as rotas são baseadas em id atualmente e não em username, então meu user por exemplo tem endereço /user/3 e não /user/thiago. Os ids foram escondidos dos templates (isso deve ter quebrados algumas coisas por enquanto).

> Mas vamos propagar username nas rotas também, o que acha?
hmmm. teoricamente vai haver colisão. como os NUSPs, que são usernames, são números inteiros, pode acontecer, depois de uns 600 anos, de os IDs alcançarem os NUSPs. talvez fazer a roda ir direto pro username faça mais sentido.
