### ISSUE TITLE
Permitir que algumas redes sejam acessíveis por qualquer usuário

### ISSUE THREAD

**Issue by wgnann** [uspdev/copaco#346]
Hoje toda rede precisa de um grupo para que ela fique visível.

Se pretendemos que o sistema seja acessível por usuários em geral, marcá-los num dado grupo torna-se uma tarefa impraticável. Ou o sistema infere em quais grupos o usuário deveria participar (mas aí entra o acoplamento com algum serviço que diga isso) ou libera algumas redes para todo mundo.

**Comment by thiagogomesverissimo** [comment]
Um checkbox no cadastro/edição de rede dizendo que a rede é ou não acessível por todos resolveria?
