### ISSUE TITLE
Não é melhor codigoUnidade que siglaUnidade no login com Oauth 1.0?

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/copaco#348]
"codigoUnidade" => 8
      "siglaUnidade" => "FFLCH"

**Comment by wgnann** [comment]
Eu pensei sobre isso. Achei que o arquivo de configuração ficaria melhor com uma lista de strings em vez de uma lista de números.

**Comment by thiagogomesverissimo** [comment]
Saquei. Só sugestão, só verificando se tinha visto. Fecahndo issue =)
