### ISSUE TITLE
Usar template USP?

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/copaco#351]

**Comment by thiagogomesverissimo** [comment]
@wgnann o que acha dessa mudança de template?

**Comment by wgnann** [comment]
Parece bem interessante. Estava pensando nisso agora que usei o laravel-usp-theme noutro projeto (baseado em laravel pela facilidade do socialite).

**Comment by thiagogomesverissimo** [comment]
Legal. Vou mandar um PR
