### ISSUE TITLE
Criar função / Helper de formatação de data

### ISSUE THREAD

**Issue by girol** [uspdev/copaco#36]
A forma que [esta linha](https://github.com/uspdev/copaco_laravel/blob/4a9fc11afe6f50b391fe51811f4304ce741937d4/app/Http/Controllers/EquipamentoController.php#L52) foi implementada está confusa e pouco legível. 

Como é usada em mais de um lugar, seria interessante criar um helper

Opções:
- Verificar se o Laravel já possui algo semelhante
- Criar uma função/helper para executar essa tarefa

**Comment by girol** [comment]
Sugestão de [receita](http://laravel-recipes.com/recipes/50/creating-a-helpers-file)

**Comment by leandroramos** [comment]
Não é necessário manipular a data. O Laravel pega o valor do campo e grava no banco com o formato necessário.

**Comment by leandroramos** [comment]
Eu corrigi o problema usando a classe Carbon, criando a data a partir da string fornecida:
Carbon::createFromFormat('d/m/Y', $request->vencimento);
No entando, errei o número da issue no commit e no branch (shame, shame...)

**Comment by girol** [comment]
@thiagogomesverissimo referencia a solução em #86
