### ISSUE TITLE
Adicionar dependências

### ISSUE THREAD

**Issue by wgnann** [uspdev/copaco#378]
Estava testando uma instalação "limpa" do copaco para tentar trazer as alterações que eu fiz no IME e ficar com um projeto só e descobri que precisa de:

1. php-dom
2. php-gd

**Comment by wgnann** [comment]
aliás, php-zip também

**Comment by wgnann** [comment]
aliás, php-zip também

**Comment by thiagogomesverissimo** [comment]
ok, vamos colocar no composer essas dependências.
