### ISSUE TITLE
Permissão de usuário da rede

### ISSUE THREAD

**Issue by oFandangos** [uspdev/copaco#399]
Se um usuário tiver permissão de admin em uma rede, ele deve ter acesso às máquinas cadastradas por outros usuários naquela rede.
Atualmente ele só pode acessar os computadores cadastrador por si próprio na rede, porém de outros não. (403 unauthorized)

**Comment by thiagogomesverissimo** [comment]
O problema está na função `temAcessoNaRedeDeUmAdminGrupo($user,$equipamento)` da classe `EquipamentoPolicy`
