### ISSUE TITLE
Quando os formulários não são validados, as mensagens flash são mostradas, mas os campos já preenchidos desaparecem. Corrigir esse comportamento para todos forms. 

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/copaco#53]

**Comment by leandroramos** [comment]
Vou resolver essa issue com prazer assim que fecharmos as funcionalidades dos formulários. O de equipamentos tem uns javascripts que demandam muita gambiarra no Blade para continuarem com o mesmo comportamento e manterem os valores digitados ao mesmo tempo. Assim que os forms estiverem prontos, adapto o JS e encerro a questão.
