### ISSUE TITLE
Implementar seeds para o banco de dados.

### ISSUE THREAD

**Issue by leandroramos** [uspdev/copaco#74]

**Comment by girol** [comment]
I'll Take this :neckbeard:

**Comment by girol** [comment]
Caraca, já fizeram ahuehuahue

**Comment by girol** [comment]
Mas tá bugada... :face_with_head_bandage:

**Comment by leandroramos** [comment]
Eu fiz num outro "momento" do banco de dados. Mudou bastante coisa.
