### ISSUE TITLE
Quando deletar rede, remover ips do equipamentos alocados naquela rede (mas não remover equipamentos).

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/copaco#80]

**Comment by fabiojm** [comment]
Como não tem como o equipamento ficar sem rede, a solução seria criar uma rede default para receber os equipamentos órfãos ?

**Comment by thiagogomesverissimo** [comment]
Acho que podemos deixar a alocação do equipamento em uma rede opcional e criar uma lista de equipamentos não alocados. Estou fazendo essa issue: #107
